
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: issuedesk-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Your_password123' -C -Q 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build:
      context: ./IssueDesk
      dockerfile: ./src/WebApi/Dockerfile
    container_name: issuedesk-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=IssueDeskDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5080:8080"

  web:
    build:
      context: ./IssueDesk/frontend
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_PROXY_TARGET=http://api:8080
    depends_on:
      - api

